# Generated by Django 5.2.8 on 2025-11-28 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_studentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='subject',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='account.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='adviser',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='number_of_students',
            field=models.IntegerField(default=0),
        ),
    ]
