# Generated by Django 5.2.8 on 2025-11-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_section_subject_alter_section_adviser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sections_covered',
        ),
        migrations.AlterField(
            model_name='section',
            name='adviser',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='number_of_students',
            field=models.IntegerField(),
        ),
    ]
