# Generated by Django 5.2.8 on 2025-11-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_assignedsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyassignment',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='account.subject'),
        ),
        migrations.RemoveField(
            model_name='facultyassignment',
            name='subject',
        ),
        migrations.AddField(
            model_name='facultyassignment',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='faculty_subjects', to='account.subject'),
        ),
    ]
