# Generated by Django 5.2.8 on 2025-11-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_facultyassignment_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='facultyassignment',
            name='subject',
        ),
        migrations.AddField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='faculties', to='account.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facultyassignment',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='account.subject'),
        ),
    ]
