# Generated by Django 5.2.8 on 2025-11-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_faculty_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='account.subject'),
        ),
    ]
