# Generated by Django 5.2.8 on 2025-11-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_faculty_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='grade_and_section',
            field=models.CharField(choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], default='active', max_length=20),
        ),
    ]
