# Generated by Django 5.2.8 on 2025-11-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_studentrecord_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade_level',
        ),
    ]
