# Generated by Django 5.2.8 on 2025-11-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='score',
            name='section',
        ),
        migrations.RemoveField(
            model_name='score',
            name='subject',
        ),
    ]
