# Generated by Django 5.2.8 on 2025-11-29 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_score_grade_remove_score_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.studentrecord'),
        ),
    ]
