# Generated by Django 5.2.8 on 2025-11-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_quizscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade_level',
            field=models.CharField(choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], default=9, max_length=10),
            preserve_default=False,
        ),
    ]
