# Generated by Django 5.2.8 on 2025-11-29 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_add_grade_level_to_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_number', models.PositiveIntegerField()),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='account.studentrecord')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='account.subject')),
            ],
            options={
                'ordering': ['subject', 'exam_number'],
                'unique_together': {('student', 'subject', 'exam_number')},
            },
        ),
        migrations.CreateModel(
            name='ProjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.PositiveIntegerField()),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_scores', to='account.studentrecord')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_scores', to='account.subject')),
            ],
            options={
                'ordering': ['subject', 'project_number'],
                'unique_together': {('student', 'subject', 'project_number')},
            },
        ),
    ]
