# Generated by Django 5.2.8 on 2025-11-29 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_add_grade_level_to_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('sessions_per_week', models.PositiveIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='account.subject')),
            ],
            options={
                'ordering': ['subject', 'week_number'],
                'unique_together': {('subject', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_1', models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], default='A', max_length=1, null=True)),
                ('session_2', models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], default='A', max_length=1, null=True)),
                ('session_3', models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], default='A', max_length=1, null=True)),
                ('session_4', models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], default='A', max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_attendance', to='account.studentrecord')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='account.weeklyattendancesession')),
            ],
            options={
                'ordering': ['session', 'student'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
