# Generated by Django 5.2.8 on 2025-11-29 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_weeklyattendancesession_weeklyattendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPredictionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('predicted_category', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('At Risk', 'At Risk')], max_length=20, null=True)),
                ('predicted_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='account.studentrecord')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='account.subject')),
            ],
            options={
                'ordering': ['-predicted_at'],
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
