# Generated by Django 5.2.8 on 2025-11-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_mlpredictionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='account_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
