# Generated by Django 5.2.8 on 2025-12-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_add_adviser_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='adviser_old',
        ),
        migrations.AddField(
            model_name='section',
            name='adviser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
